services:
  - type: web
    name: resume-app
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: resume-app-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false

databases:
  - name: resume-app-db
    databaseName: resume_app_production
    user: resume_app 